title: mEnglish
subtitle: Tiếng Anh trực tuyến
description: >- # this means to ignore newlines until "baseurl:"
  Học tiếng Anh 1-1 với giáo viên người Philippines.
author: Hoàng Phan
email: hoangpm.qn96@gmail.com
avatar: assets/images/logomenglish@3x.png

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url: https://facebook.com/hoangpm96
googleplus_url:
instagram_url:
linkedin_url:
github_url:
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
